---
- name: Install nginx
  become: "{{ nginx.become }}"
  apt: name=nginx state=present

- name: Remove default sites
  become: "{{ nginx.become }}"
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/sites-enabled/default
  notify: reload nginx
  tags:
    - nginx-config

- name: Upload sites
  become: "{{ nginx.become }}"
  template:
    src: sites/{{ item }}.conf.j2
    dest: /etc/nginx/conf.d/{{ item }}.conf
  with_items: "{{ nginx.sites }}"
  notify: reload nginx
  tags:
    - nginx-config

- name: Upload backends
  become: "{{ nginx.become }}"
  template:
    src: backends.j2
    dest: /etc/nginx/conf.d/backends
  notify: reload nginx
  tags:
    - nginx-config
    - nginx-config-backends

- name: Start and enable nginx service
  become: "{{ nginx.become }}"
  service: name=nginx state=started enabled=yes
  when: nginx.systemd
